project_id = "snqrnpphjjskjtupwlfp"

[functions.ai-meal-suggestions]
verify_jwt = false

[functions.analyze-food-image]
verify_jwt = false

[functions.ai-diet-suggestions]
verify_jwt = false

[functions.ai-daily-suggestions]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.strict-mode-compliance]
verify_jwt = false

[functions.strict-mode-meal-analyze]
verify_jwt = false

[functions.ai-pantry-suggestions]
verify_jwt = false

[functions.weekly-insight]
verify_jwt = false

[functions.personalised-recommendations]
verify_jwt = false

[functions.behaviour-analysis]
verify_jwt = false

[functions.analyze-food-snap]
verify_jwt = false

[functions.food-behaviour-engine]
verify_jwt = false
