// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.2";

// src/lib/mcp/tools/get-daily-summary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z } from "npm:zod@^4.5.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to Nutrio to use this tool." }],
    isError: true
  };
}
function todayISO() {
  return (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
}

// src/lib/mcp/tools/get-daily-summary.ts
var get_daily_summary_default = defineTool({
  name: "get_daily_summary",
  title: "Get daily nutrition summary",
  description: "Get the signed-in user's calories, macros, water and workouts for a given day, compared with their targets.",
  inputSchema: {
    date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Day to summarise in YYYY-MM-DD format. Defaults to today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const day = date ?? todayISO();
    const from = `${day}T00:00:00.000Z`;
    const to = `${day}T23:59:59.999Z`;
    const supabase = supabaseForUser(ctx);
    const [profileRes, foodRes, waterRes, workoutRes] = await Promise.all([
      supabase.from("profiles").select("calorie_target, protein_target, carbs_target, fat_target, fibre_target").maybeSingle(),
      supabase.from("food_logs").select("food_name, meal_type, calories, protein, carbs, fat, fibre").gte("logged_at", from).lte("logged_at", to),
      supabase.from("water_logs").select("glasses").gte("logged_at", from).lte("logged_at", to),
      supabase.from("workout_logs").select("exercise_name, duration_minutes, calories_burned").gte("logged_at", from).lte("logged_at", to)
    ]);
    const error = profileRes.error ?? foodRes.error ?? waterRes.error ?? workoutRes.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const foods = foodRes.data ?? [];
    const sum = (key) => Math.round(foods.reduce((total, row) => total + (Number(row[key]) || 0), 0));
    const summary = {
      date: day,
      totals: {
        calories: sum("calories"),
        protein_g: sum("protein"),
        carbs_g: sum("carbs"),
        fat_g: sum("fat"),
        fibre_g: sum("fibre")
      },
      targets: profileRes.data ?? null,
      water_glasses: (waterRes.data ?? []).reduce((t, r) => t + (Number(r.glasses) || 0), 0),
      meals_logged: foods.length,
      foods,
      workouts: workoutRes.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/get-progress.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z2 } from "npm:zod@^4.5.4";
var get_progress_default = defineTool2({
  name: "get_progress",
  title: "Get recent progress",
  description: "Get the signed-in user's goal profile, recent weight history and recent daily calorie totals over a number of days.",
  inputSchema: {
    days: z2.number().int().min(1).max(90).optional().describe("How many days back to look. Defaults to 14.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const window = days ?? 14;
    const since = new Date(Date.now() - window * 864e5);
    const sinceISO = since.toISOString();
    const sinceDay = sinceISO.slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const [profileRes, weightRes, foodRes] = await Promise.all([
      supabase.from("profiles").select("*").maybeSingle(),
      supabase.from("weight_history").select("recorded_on, weight_kg").gte("recorded_on", sinceDay).order("recorded_on", { ascending: true }),
      supabase.from("food_logs").select("logged_at, calories, protein").gte("logged_at", sinceISO)
    ]);
    const error = profileRes.error ?? weightRes.error ?? foodRes.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byDay = {};
    for (const row of foodRes.data ?? []) {
      const day = String(row.logged_at).slice(0, 10);
      byDay[day] ??= { calories: 0, protein: 0 };
      byDay[day].calories += Number(row.calories) || 0;
      byDay[day].protein += Number(row.protein) || 0;
    }
    const daily = Object.entries(byDay).sort(([a], [b]) => a.localeCompare(b)).map(([date, v]) => ({ date, calories: Math.round(v.calories), protein_g: Math.round(v.protein) }));
    const result = {
      window_days: window,
      profile: profileRes.data ?? null,
      weight_history: weightRes.data ?? [],
      daily_calories: daily
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/log-food.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z3 } from "npm:zod@^4.5.4";
var log_food_default = defineTool3({
  name: "log_food",
  title: "Log a food item",
  description: "Add a food item with its calories and macros to the signed-in user's diary.",
  inputSchema: {
    food_name: z3.string().trim().min(1).describe("Name of the food or meal."),
    meal_type: z3.enum(["breakfast", "lunch", "dinner", "snacks"]).describe("Which meal this food belongs to."),
    calories: z3.number().nonnegative().describe("Calories (kcal)."),
    protein: z3.number().nonnegative().optional().describe("Protein in grams."),
    carbs: z3.number().nonnegative().optional().describe("Carbohydrates in grams."),
    fat: z3.number().nonnegative().optional().describe("Fat in grams."),
    fibre: z3.number().nonnegative().optional().describe("Fibre in grams."),
    quantity: z3.number().positive().optional().describe("Portion quantity, defaults to 1."),
    unit: z3.string().trim().optional().describe("Portion unit, e.g. g, ml, serving.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("food_logs").insert({
      user_id: ctx.getUserId(),
      food_name: input.food_name,
      meal_type: input.meal_type,
      calories: input.calories,
      protein: input.protein ?? 0,
      carbs: input.carbs ?? 0,
      fat: input.fat ?? 0,
      fibre: input.fibre ?? 0,
      quantity: input.quantity ?? 1,
      unit: input.unit ?? "serving",
      logged_at: (/* @__PURE__ */ new Date()).toISOString()
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${input.food_name} (${input.calories} kcal) to ${input.meal_type}.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/log-water.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z4 } from "npm:zod@^4.5.4";
var log_water_default = defineTool4({
  name: "log_water",
  title: "Log water intake",
  description: "Record glasses of water for the signed-in user.",
  inputSchema: {
    glasses: z4.number().int().min(1).max(30).describe("Number of glasses of water to add.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ glasses }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("water_logs").insert({ user_id: ctx.getUserId(), glasses, logged_at: (/* @__PURE__ */ new Date()).toISOString() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${glasses} glass(es) of water.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/log-workout.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z5 } from "npm:zod@^4.5.4";
var log_workout_default = defineTool5({
  name: "log_workout",
  title: "Log a workout",
  description: "Record a completed workout for the signed-in user.",
  inputSchema: {
    exercise_name: z5.string().trim().min(1).describe("Name of the exercise or session."),
    exercise_type: z5.enum(["strength", "core", "endurance", "yoga", "other"]).describe("Category of the workout."),
    duration_minutes: z5.number().int().positive().describe("Duration in minutes."),
    calories_burned: z5.number().nonnegative().optional().describe("Estimated calories burned."),
    intensity: z5.enum(["low", "moderate", "high"]).optional().describe("Perceived intensity."),
    notes: z5.string().trim().optional().describe("Optional notes about the session.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("workout_logs").insert({
      user_id: ctx.getUserId(),
      exercise_name: input.exercise_name,
      exercise_type: input.exercise_type,
      duration_minutes: input.duration_minutes,
      calories_burned: input.calories_burned ?? 0,
      intensity: input.intensity ?? "moderate",
      notes: input.notes ?? null,
      logged_at: (/* @__PURE__ */ new Date()).toISOString()
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${input.exercise_name} for ${input.duration_minutes} minutes.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/log-weight.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z6 } from "npm:zod@^4.5.4";
var log_weight_default = defineTool6({
  name: "log_weight",
  title: "Log body weight",
  description: "Record the signed-in user's body weight for a given day.",
  inputSchema: {
    weight_kg: z6.number().positive().max(500).describe("Body weight in kilograms."),
    recorded_on: z6.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date of the reading in YYYY-MM-DD format. Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ weight_kg, recorded_on }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("weight_history").insert({ user_id: ctx.getUserId(), weight_kg, recorded_on: recorded_on ?? todayISO() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${weight_kg} kg.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "snqrnpphjjskjtupwlfp";
var mcp_default = defineMcp({
  name: "nutrio-your-uk-nutrition-coach",
  title: "Nutrio: Your UK Nutrition Coach",
  version: "0.1.0",
  instructions: "Tools for Nutrio, a UK nutrition and fitness coach app. Use `get_daily_summary` for today's calories, macros, water and workouts against the user's targets, `get_progress` for weight and calorie trends, and the `log_*` tools to record food, water, workouts and body weight for the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_daily_summary_default, get_progress_default, log_food_default, log_water_default, log_workout_default, log_weight_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
